version: "3.9"
services:
  gosh:
    container_name: gosh
    image: stenehall/gosh:latest
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./config.yml:/config.yml
      - ./favicons:/favicons
    ports:
      - "8080:8080"
